### ISSUE TITLE
subfolder installation compatibility?

### ISSUE THREAD

**Issue by AliCihan** [Schamper/nodebb-plugin-cards#12]
We have our NodeBB forum installed at subfolder as /forum... 

This plugin does not seem to be working on our forum (NodeBB 1.18.6). Can you please check if it is compatible with subfolder installation?

**Comment by AliCihan** [comment]
@Schamper it works on our development forum which is at XXX.com ; however does not work on the prod, which is at XXX.com/forum

**Comment by barisusakli** [comment]
https://github.com/Schamper/nodebb-plugin-cards/pull/14/files

**Comment by AliCihan** [comment]
thanks @barisusakli
