### ISSUE TITLE
Compatibility with V3.X

### ISSUE THREAD

**Issue by DroidBV8** [Schamper/nodebb-plugin-cards#16]
Hello @Schamper 

Is there any intention to make the nodebb-plugin-cards compatible with nodebb v3.x ? 

Thanks

**Comment by Schamper** [comment]
Hi @DroidBV8, unfortunately not. However I’d be more than happy to accept a pull request and publish the new version, or to transfer the ownership to @Nodebb-community.

**Comment by barisusakli** [comment]
https://github.com/Schamper/nodebb-plugin-cards/pull/17

![image](https://github.com/Schamper/nodebb-plugin-cards/assets/2583394/3d6b9b99-50c3-434c-b8e5-7c79738ea993)

**Comment by barisusakli** [comment]
@Schamper feel free to transfer to https://github.com/NodeBB-Community after you merge and publish

**Comment by Schamper** [comment]
Merged and published, I'll contact you for transferring ownership.
