### ISSUE TITLE
add button to follow user

### ISSUE THREAD

**Issue by exomarty** [Schamper/nodebb-plugin-cards#8]
like persona hovercard 
would be cool adition

**Comment by exomarty** [comment]
layout example
![screenshot_5](https://cloud.githubusercontent.com/assets/10746278/14514623/b013bd3e-01f2-11e6-9f82-fcdc0eb8b884.png)
![screenshot_4](https://cloud.githubusercontent.com/assets/10746278/14514626/b27872c2-01f2-11e6-855a-ba8b4319585b.png)

**Comment by revir** [comment]
@exomarty 
I add this feature on [nodebb-plugin-cards2](https://github.com/revir/nodebb-plugin-cards2), and used on [my website](https://v2mm.tech). check it :)

**Comment by barisusakli** [comment]
@Schamper can close this, the card has follow/unfollow button
